import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import {  Providers } from "../components/Provider";
import { ThemeProvider } from "@/components/theme-provider";
import Navbar from "@/components/Navbar";
import { Footer } from "@/components/Footer";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <Providers>

    <html lang="en" suppressHydrationWarning>
      <ThemeProvider  attribute="class"
        defaultTheme="system"
        enableSystem
        disableTransitionOnChange>
      <body
        className={` antialiased  mx-auto px-2 sm:px-4 pt-4 sm:pt-4 `}
        >
          <main className="flex flex-col justify-between items-center">

             <Navbar />
             <section className="flex-1">
              
        {children}
             </section>
        <Footer/>
          </main>
      </body>
          </ThemeProvider>
    </html>
        </Providers>
  );
}
